PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>
PREFIX td: <https://www.w3.org/2019/wot/td#>
PREFIX wotsec: <https://www.w3.org/2019/wot/security#>
PREFIX htv: <http://www.w3.org/2011/http#>
PREFIX hctl: <https://www.w3.org/2019/wot/hypermedia#>
PREFIX js: <https://www.w3.org/2019/wot/json-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT {
    GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-florence#>
    {
        ?farm hmas:contains ?LandSection1.
        ?farm hmas:contains ?LandSection2.
        ?farm hmas:contains ?LandSection3.
        ?farm hmas:contains ?LandSection4.
        ?LandSection1 a td:Thing, was:LandSection;
  			td:title "Landsection1 of the farm";
  			td:hasSecurityConfiguration [ a wotsec:NoSecurityScheme];

.
        ?LandSection4 a td:Thing, was:LandSection;
  			td:title "Landsection2 of the farm";
  			td:hasSecurityConfiguration [ a wotsec:NoSecurityScheme];

     .
                ?LandSection2 a td:Thing, was:LandSection;
  			td:title "Landsection3 of the farm";
  			td:hasSecurityConfiguration [ a wotsec:NoSecurityScheme];

     .
                ?LandSection3 a td:Thing, was:LandSection;
  			td:title "Landsection4 of the farm";
  			td:hasSecurityConfiguration [ a wotsec:NoSecurityScheme];

     .
    }.
} WHERE {
	?farm a was:Farm.
  	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-florence#LandSection-1")) AS ?LandSection1)
    BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-florence#LandSection-2")) AS ?LandSection2)
    BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-florence#LandSection-3")) AS ?LandSection3)
    BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-florence#LandSection-4")) AS ?LandSection4)
}